services:

  bun-app:
    build:
      context: ./bun
    ports:
      - 4000:4000
    volumes:
      - ./bun:/usr/src/app
      - ~/.aws:/home/bun/.aws
    env_file:
      - path: ./.env

  express-app:
    build:
      context: ./express
    ports:
      - 4001:3000
    volumes:
      - ./express:/usr/src/app
      - ~/.aws:/home/node/.aws
    env_file:
      - path: ./.env

  fastify-app:
    build:
      context: ./fastify
    ports:
      - 4002:3000
    volumes:
      - ./fastify:/usr/src/app
      - ~/.aws:/home/node/.aws
    env_file:
      - path: ./.env


  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   environment:
  #     RABBITMQ_DEFAULT_USER: rabbitmq
  #     RABBITMQ_DEFAULT_PASS: rabbitmq
