services:
  image-handler:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
