services:

  express-app:
    build:
      context: ./express
    ports:
      - 4002:5000
    volumes:
      - ./express:/usr/src/app
      - ~/.aws:/home/node/.aws
    env_file:
      - path: ./.env

  fastify-app:
    build:
      context: ./fastify
    ports:
      - 4003:3000
    volumes:
      - ./fastify:/usr/src/app
      - ~/.aws:/home/node/.aws
    env_file:
      - path: ./.env

  localstack:
    image: localstack/localstack:1.0.4
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      SERVICES: s3,sns
      DEBUG: 1
      DEFAULT_REGION: us-east-1
      DATA_DIR: /tmp/localstack/data
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
      USE_SSL: false
      CONFIG_DIR: .
      CONFIG_PROFILE: localstack
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:4566/_localstack/health"
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s

  aws-cli:
    image: amazon/aws-cli
    volumes:
      - ./bucket:/aws
    depends_on:
      localstack:
        condition: service_healthy
    env_file:
      - path: ./.env
    entrypoint: /bin/sh -c
    command: >
      "
        aws --endpoint-url=http://localstack:4566 s3 ls
        aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket image-test --region us-east-1
        aws --endpoint-url=http://localstack:4566 sns create-topic --name upload
      "
  # influxdb:
  #   image: influxdb:1.8
  #   ports:
  #     - "8086:8086"
  #   environment:
  #     - INFLUXDB_DB=k6

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #     - GF_AUTH_ANONYMOUS_ENABLED=true
  #     - GF_AUTH_BASIC_ENABLED=false
  #   volumes:
  #     - ./grafana:/etc/grafana/provisioning/
